# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4780a8144f1f6c6d58fe1cc7b483a500f9ac159cedfe16f53abdb7b517a0e06ba28280624b478e5cb91d11a91b2722fb71bbcf5f5881b20d6901c51a1b0f606b

test:
  secret_key_base: 74550951d4a32c39ac94a3f29296f1a7324c2cfbeb4ab2134a43567ef6ef4f562313e5b2eec711aeb7e863f936e3b7ce6ed046df69c3642b3d5b9ee693f64948

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
